version: '3'

services:
  app:
    build: .
    container_name: fastapi-gino-postgres
    image: fastapi-gino-postgres
    env_file: .env
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    ports:
      - 80:80
