[tool.poetry]
name = "fastapi-gino-arq-uvicorn"
version = "0.4.0"
description = "High-performance Async REST API, in Python. FastAPI + GINO + Arq + Uvicorn (w/ Redis and PostgreSQL)."

[tool.poetry.dependencies]
python = "^3.8"